export const ADD_NEW_POST = 'ADD-NEW-POST';
export const CHANGE_PHOTO_SUCCESS = 'CHANGE_PHOTO_SUCCESS';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_USER_STATUS = 'SET_USER_STATUS';
