export const APPS = {
  INITIALIZED_SUCCESS: 'APPS_INITIALIZED_SUCCESS',
  INITIALIZED: 'APPS_INITIALIZED',
};

export const AUTHS = {
  OWN_AUTH_SUCCESS: 'AUTHS_OWN_AUTH_SUCCESS',
  CAPTCHA_SUCCESS: 'AUTHS_CAPTCHA_SUCCESS',
  OWN_PROFILE: 'AUTHS_OWN_PROFILE',
  LOGOUT: 'AUTHS_LOGOUT',
  CAPTCHA_URL: 'AUTHS_CAPTCHA_URL',
  LOGIN: 'AUTHS_LOGIN',
};

export const DIALOGS = {
  MESSAGE: 'DIALOGS_MESSAGE',
};

export const PROFILES = {
  SET_NEW_POST_SUCCESS: 'PROFILES_SET_NEW_POST_SUCCESS',
  UPDATE_PHOTO_SUCCESS: 'PROFILES_UPDATE_PHOTO_SUCCESS',
  SET_USER_PROFILE_SUCCESS: 'PROFILES_SET_USER_PROFILE_SUCCESS',
  SET_USER_STATUS_SUCCESS: 'PROFILES_SET_USER_STATUS_SUCCESS',
  GET_USER_PROFILE: 'PROFILES_GET_USER_PROFILE',
  GET_USER_STATUS: 'PROFILES_GET_USER_STATUS',
  UPDATE_USER_STATUS: 'PROFILES_UPDATE_USER_STATUS',
  UPDATE_PHOTO: 'PROFILES_UPDATE_PHOTO',
  UPDATE_INFO: 'PROFILES_UPDATE_INFO',
};

export const SIDEBARS = {
  SET_EXCHANGE_RATE_SUCCESS: 'SIDEBARS_SET_EXCHANGE_RATE_SUCCESS',
  GET_RATES: 'SIDEBARS_GET_RATES',
};

export const USERS = {
  IS_ANSVER_GONE: 'USERS_IS_ANSVER_GONE',
  IS_UPLOADED: 'USERS_IS_UPLOADED',
  SET_USERS_SUCCESS: 'USERS_SET_USERS_SUCCESS',
  SET_USERS_PAGE_SUCCESS: 'USERS_SET_USERS_PAGE_SUCCESS',
  SUBSCRIBE_SUCCESS: 'USERS_SUBSCRIBE_SUCCESS',
  UNSUBSCRIBE_SUCCESS: 'USERS_UNSUBSCRIBE_SUCCESS',
  TOTAL_AMOUNT_USERS: 'USERS_TOTAL_AMOUNT_USERS',
  LOAD_USERS: 'USERS_LOAD_USERS',
  LOAD_FOLLOW: 'USERS_LOAD_FOLLOW',
  LOAD_UNFOLLOW: 'USERS_LOAD_UNFOLLOW',
};
